[package]
name = "diffamer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tempfile = "3.10"
clap = { version = "4.5", features = ["derive"] }
natord = "1.0"
similar = "2.7.0"
console = "0.16"
